// Auto-generated by Supabase (`generate_typescript_types`). Do not hand-edit —
// regenerate after every schema migration.
// NOTE: the zatca_keys table, invoices.zatca_* columns, and
// zatca_reserve_sequence/zatca_finalize_signature functions below were
// hand-authored to match migration 0012 because no live Supabase project was
// connected when that migration was written — regenerate this file for real
// once the migration has been applied to confirm it matches exactly.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      companies: {
        Row: {
          address: string
          business_type: string
          city: string
          cr_number: string
          email: string
          legal_name: string
          name: string
          phone: string
          updated_at: string
          vat_number: string
          workspace_id: string
        }
        Insert: {
          address?: string
          business_type?: string
          city?: string
          cr_number?: string
          email?: string
          legal_name?: string
          name?: string
          phone?: string
          updated_at?: string
          vat_number?: string
          workspace_id: string
        }
        Update: {
          address?: string
          business_type?: string
          city?: string
          cr_number?: string
          email?: string
          legal_name?: string
          name?: string
          phone?: string
          updated_at?: string
          vat_number?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "companies_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: true
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      customers: {
        Row: {
          address: string
          company: string
          created_at: string
          email: string
          id: string
          name: string
          notes: string
          phone: string
          vat_number: string
          workspace_id: string
        }
        Insert: {
          address?: string
          company?: string
          created_at?: string
          email?: string
          id?: string
          name?: string
          notes?: string
          phone?: string
          vat_number?: string
          workspace_id: string
        }
        Update: {
          address?: string
          company?: string
          created_at?: string
          email?: string
          id?: string
          name?: string
          notes?: string
          phone?: string
          vat_number?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "customers_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      invoice_events: {
        Row: {
          created_at: string
          event_type: string
          id: string
          invoice_id: string
          payload: Json
          workspace_id: string
        }
        Insert: {
          created_at?: string
          event_type: string
          id?: string
          invoice_id: string
          payload?: Json
          workspace_id: string
        }
        Update: {
          created_at?: string
          event_type?: string
          id?: string
          invoice_id?: string
          payload?: Json
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "invoice_events_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "invoices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoice_events_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      invoice_line_items: {
        Row: {
          id: string
          invoice_id: string
          name: string
          product_id: string | null
          quantity: number
          sort_order: number
          unit_price: number
          vat_rate: number
        }
        Insert: {
          id?: string
          invoice_id: string
          name: string
          product_id?: string | null
          quantity?: number
          sort_order?: number
          unit_price?: number
          vat_rate?: number
        }
        Update: {
          id?: string
          invoice_id?: string
          name?: string
          product_id?: string | null
          quantity?: number
          sort_order?: number
          unit_price?: number
          vat_rate?: number
        }
        Relationships: [
          {
            foreignKeyName: "invoice_line_items_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "invoices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoice_line_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      invoices: {
        Row: {
          created_at: string
          customer_id: string | null
          discount_percent: number
          due_date: string
          id: string
          issue_date: string
          notes: string
          number: string
          paid_date: string | null
          status: string
          updated_at: string
          workspace_id: string
          zatca_icv: number | null
          zatca_invoice_hash: string | null
          zatca_previous_hash: string | null
          zatca_public_key: string | null
          zatca_signature: string | null
          zatca_signed_at: string | null
        }
        Insert: {
          created_at?: string
          customer_id?: string | null
          discount_percent?: number
          due_date: string
          id?: string
          issue_date: string
          notes?: string
          number: string
          paid_date?: string | null
          status?: string
          updated_at?: string
          workspace_id: string
          zatca_icv?: number | null
          zatca_invoice_hash?: string | null
          zatca_previous_hash?: string | null
          zatca_public_key?: string | null
          zatca_signature?: string | null
          zatca_signed_at?: string | null
        }
        Update: {
          created_at?: string
          customer_id?: string | null
          discount_percent?: number
          due_date?: string
          id?: string
          issue_date?: string
          notes?: string
          number?: string
          paid_date?: string | null
          status?: string
          updated_at?: string
          workspace_id?: string
          zatca_icv?: number | null
          zatca_invoice_hash?: string | null
          zatca_previous_hash?: string | null
          zatca_public_key?: string | null
          zatca_signature?: string | null
          zatca_signed_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "invoices_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          active: boolean
          created_at: string
          description: string
          id: string
          name: string
          unit_price: number
          vat_category: string
          workspace_id: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          description?: string
          id?: string
          name?: string
          unit_price?: number
          vat_category?: string
          workspace_id: string
        }
        Update: {
          active?: boolean
          created_at?: string
          description?: string
          id?: string
          name?: string
          unit_price?: number
          vat_category?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "products_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          display_name: string
          id: string
          locale: string
        }
        Insert: {
          created_at?: string
          display_name?: string
          id: string
          locale?: string
        }
        Update: {
          created_at?: string
          display_name?: string
          id?: string
          locale?: string
        }
        Relationships: []
      }
      settings: {
        Row: {
          currency: string
          default_due_days: number
          default_notes: string
          default_vat_rate: number
          invoice_prefix: string
          next_invoice_number: number
          onboarded: boolean
          updated_at: string
          workspace_id: string
        }
        Insert: {
          currency?: string
          default_due_days?: number
          default_notes?: string
          default_vat_rate?: number
          invoice_prefix?: string
          next_invoice_number?: number
          onboarded?: boolean
          updated_at?: string
          workspace_id: string
        }
        Update: {
          currency?: string
          default_due_days?: number
          default_notes?: string
          default_vat_rate?: number
          invoice_prefix?: string
          next_invoice_number?: number
          onboarded?: boolean
          updated_at?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "settings_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: true
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      zatca_keys: {
        Row: {
          created_at: string
          last_icv: number
          private_key_pem: string
          public_key_pem: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          last_icv?: number
          private_key_pem: string
          public_key_pem: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          last_icv?: number
          private_key_pem?: string
          public_key_pem?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "zatca_keys_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: true
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      workspace_members: {
        Row: {
          created_at: string
          role: Database["public"]["Enums"]["workspace_role"]
          user_id: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          role?: Database["public"]["Enums"]["workspace_role"]
          user_id: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          role?: Database["public"]["Enums"]["workspace_role"]
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "workspace_members_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      workspaces: {
        Row: {
          created_at: string
          id: string
          name: string
          owner_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          owner_id: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          owner_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      bootstrap_workspace: { Args: { p_name: string }; Returns: string }
      create_invoice: {
        Args: {
          p_customer_id: string
          p_discount_percent: number
          p_due_date: string
          p_id: string
          p_issue_date: string
          p_items: Json
          p_notes: string
          p_status: string
          p_workspace_id: string
        }
        Returns: {
          created_at: string
          customer_id: string | null
          discount_percent: number
          due_date: string
          id: string
          issue_date: string
          notes: string
          number: string
          paid_date: string | null
          status: string
          updated_at: string
          workspace_id: string
          zatca_icv: number | null
          zatca_invoice_hash: string | null
          zatca_previous_hash: string | null
          zatca_public_key: string | null
          zatca_signature: string | null
          zatca_signed_at: string | null
        }
        SetofOptions: {
          from: "*"
          to: "invoices"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      is_workspace_admin: { Args: { ws_id: string }; Returns: boolean }
      is_workspace_member: { Args: { ws_id: string }; Returns: boolean }
      peek_invoice_number: { Args: { p_workspace_id: string }; Returns: string }
      zatca_reserve_sequence: {
        Args: { p_invoice_id: string; p_workspace_id: string }
        Returns: { icv: number; previous_hash: string }[]
      }
      zatca_finalize_signature: {
        Args: {
          p_invoice_hash: string
          p_invoice_id: string
          p_public_key: string
          p_signature: string
          p_ubl_xml: string
          p_workspace_id: string
        }
        Returns: undefined
      }
    }
    Enums: {
      workspace_role: "owner" | "admin" | "member"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      workspace_role: ["owner", "admin", "member"],
    },
  },
} as const
